package ch.aegis.contract;

import ch.aegis.model.Attribute;
import java.util.NoSuchElementException;
import java.util.Set;

/**
 * The {@link AttributeResolutionService} is responsible for resolving attributes from a given set
 * of parameters. This is mainly used in the automatically-generated code to resolve endpoint
 * arguments to the proper set of attributes used in the policy definitions. An implementation of
 * this service is automatically generated by the Aegis framework, and should not be implemented
 * unless there is a specific need to do so.
 *
 * @author Loïc Herman
 * @author Massimo Stefani
 * @author Quentin Surdez
 * @since 1.0
 */
public interface AttributeResolutionService {

    /**
     * Attempts to resolve an attribute from the given parameters.
     *
     * @param <R>        the type of the resolved attribute
     * @param params     the parameters to resolve the attribute from
     * @param targetType the target type of the attribute
     * @throws NoSuchElementException if none of the given attributes can be converted
     */
    <R extends Attribute> R resolve(Set<? extends Attribute> params, Class<R> targetType);
}
