
    create table app_user (
        user_id uuid not null,
        username varchar(48) not null,
        email varchar(255) not null,
        origin varchar(32) not null check (origin in ('AARGAU','APPENZELL_INNERRHODEN','APPENZELL_AUSSERRHODEN','BERN','BASEL_LAND','BASEL_STADT','FRIBOURG','GENEVE','GLARUS','GRAUBUNDEN','JURA','LUZERN','NEUCHATEL','NIDWALDEN','OBWALDEN','SCHAFFHAUSEN','SCHWYZ','SOLOTHURN','ST_GALLEN','THURGAU','TICINO','URI','WALLIS','VAUD','ZUG','ZURICH')),
        password varchar(324) not null,
        primary key (user_id),
        constraint uk_user_email unique (email),
        constraint uk_user_username unique (username)
    );

    create table app_user_role (
        user_fk uuid not null,
        user_role varchar(16) not null check (user_role in ('ADMINISTRATOR','MODERATOR','REVIEWER','USER')),
        primary key (user_fk, user_role)
    );

    create table app_user_token (
        user_token_id bigint generated by default as identity,
        expired boolean not null,
        refresh_token varchar(255) not null,
        revoked boolean not null,
        token varchar(255) not null,
        app_user_fk uuid not null,
        primary key (user_token_id)
    );

    create table review (
        review_id bigint generated by default as identity,
        body TEXT not null,
        status varchar(16) not null check (status in ('DRAFT','PENDING_REVIEW','VERIFIED')),
        title varchar(250) not null,
        author_fk uuid not null,
        wine_fk bigint not null,
        primary key (review_id)
    );

    create table review_comment (
        comment_id bigint generated by default as identity,
        body TEXT not null,
        author_fk uuid not null,
        review_fk bigint not null,
        primary key (comment_id)
    );

    create table wine (
        wine_id bigint generated by default as identity,
        name varchar(100) not null,
        origin varchar(32) not null check (origin in ('AARGAU','APPENZELL_INNERRHODEN','APPENZELL_AUSSERRHODEN','BERN','BASEL_LAND','BASEL_STADT','FRIBOURG','GENEVE','GLARUS','GRAUBUNDEN','JURA','LUZERN','NEUCHATEL','NIDWALDEN','OBWALDEN','SCHAFFHAUSEN','SCHWYZ','SOLOTHURN','ST_GALLEN','THURGAU','TICINO','URI','WALLIS','VAUD','ZUG','ZURICH')),
        region varchar(24) not null check (region in ('GENEVA','TICINO','THREE_LAKES','GERMAN_SWITZERLAND','VALAIS','VAUD')),
        vintner varchar(50) not null,
        primary key (wine_id)
    );

    create table wine_variety (
        wine_fk bigint not null,
        variety varchar(32) not null check (variety in ('ALIGOTE','AMIGNE','ANCELLOTTA','BARBERA','BONDOLA','CABERNET_BLANC','CABERNET_FRANC','CABERNET_JURA','CABERNET_SAUVIGNON','CARMINOIR','CHARDONNAY','CHASSELAS','COMPLETER','CORNALIN','DIOLINOIR','DIVICO','DIVONA','DORAL','DUNKELFELDER','GALOTTA','GAMARET','GAMAY','GARANOIR','GEWURZTRAMINER','HEIDA','HUMAGNE_BLANCHE','HUMAGNE_ROUGE','JOHANNISBERG','MARSANNE_BLANCHE','MERLOT','MULLER_THURGAU','MUSCAT_BLANC','NEBBIOLO','PETITE_ARVINE','PINOT_GRIS','PINOT_NOIR','RAUSCHLING','RIESLING','SAUVIGNON_BLANC','SAVAGNIN_BLANC','SEMILLON','SILVANER','SYRAH','VIOGNIER')),
        primary key (wine_fk, variety)
    );

    alter table if exists app_user_role 
       add constraint fk_user_role__user 
       foreign key (user_fk) 
       references app_user;

    alter table if exists app_user_token 
       add constraint fk_token__user 
       foreign key (app_user_fk) 
       references app_user;

    alter table if exists review 
       add constraint fk_review__author 
       foreign key (author_fk) 
       references app_user;

    alter table if exists review 
       add constraint fk_review__wine 
       foreign key (wine_fk) 
       references wine;

    alter table if exists review_comment 
       add constraint fk_comment__author 
       foreign key (author_fk) 
       references app_user;

    alter table if exists review_comment 
       add constraint fk_comment__review 
       foreign key (review_fk) 
       references review;

    alter table if exists wine_variety 
       add constraint fk_wine_variety__wine 
       foreign key (wine_fk) 
       references wine;
