FROM gradle:jdk21-alpine as builder

COPY --chown=gradle:gradle build.gradle.kts /app/
COPY --chown=gradle:gradle settings.gradle.kts /app/
COPY --chown=gradle:gradle aegis /app/aegis
COPY --chown=gradle:gradle vineward/backend /app/vineward/backend
WORKDIR /app

RUN --mount=type=cache,target=~/.gradle gradle clean vineward:vineward:bootJar --no-daemon --stacktrace

FROM eclipse-temurin:21-jre-alpine AS runner

COPY --from=builder /app/vineward/backend/build/libs/*.jar /app/app.jar
WORKDIR /app

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
