FROM node:alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

COPY . /app
WORKDIR /app

FROM base AS build

ARG API_BASE_URL=""
ARG NUXT_UI_PRO_LICENSE=""
ENV API_BASE_URL=$API_BASE_URL
ENV NUXT_UI_PRO_LICENSE=$NUXT_UI_PRO_LICENSE

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run generate

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
