package ch.aegis.processor.internal.generator;

import ch.aegis.processor.internal.util.AnnotationProcessorContext;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import java.io.IOException;
import java.util.Comparator;
import java.util.Optional;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;

/**
 * Generates default attribute providers for role enums. These providers fetch roles from Spring
 * Security's context holder, handling the standard ROLE_ prefix pattern.
 *
 * @author Loïc Herman
 * @author Massimo Stefani
 * @author Quentin Surdez
 * @since 1.0
 */
public final class DefaultRoleAttributeProviderGenerator {

    private static final ClassName COMPONENT = ClassName.get(
        "org.springframework.stereotype",
        "Component"
    );
    private static final ClassName SECURITY_CONTEXT_HOLDER = ClassName.get(
        "org.springframework.security.core.context",
        "SecurityContextHolder"
    );
    private static final ClassName GRANTED_AUTHORITY = ClassName.get(
        "org.springframework.security.core",
        "GrantedAuthority"
    );

    private static final String GENERATED_PACKAGE = "ch.aegis.provider";

    private final AnnotationProcessorContext context;
    private final TypeElement roleEnum;
    private final String className;

    private DefaultRoleAttributeProviderGenerator(
        AnnotationProcessorContext context,
        TypeElement roleEnum
    ) {
        this.context = context;
        this.roleEnum = roleEnum;
        this.className = roleEnum.getSimpleName() + "AttributeProvider";
    }

    public void generate() throws IOException {
        var classBuilder = TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addAnnotation(COMPONENT)
            .addAnnotation(GeneratorUtils.createGeneratedAnnotation())
            .addSuperinterface(
                ParameterizedTypeName.get(
                    ClassName.get("ch.aegis.contract", "AttributeProvider"),
                    ClassName.get(roleEnum)
                )
            )
            .addJavadoc(
                """
                Default attribute provider for the {@link $L} enum implementing
                {@link ch.aegis.model.Attribute}. It is fetched from the Spring security context holder by
                default. This is mainly generated to avoid boilerplate code, though it requires the security
                configuration to follow the standard {@link org.springframework.security.core.GrantedAuthority}
                pattern, where roles are prefixed with {@code ROLE_}.

                @generated by DefaultRoleProviderGenerator
                """,
                roleEnum.getQualifiedName()
            );

        addPrefixConstant(classBuilder);
        addGetAttributeTypeMethod(classBuilder);
        addProvideMethod(classBuilder);

        var javaFile = JavaFile.builder(GENERATED_PACKAGE, classBuilder.build())
            .skipJavaLangImports(true)
            .build();

        javaFile.writeTo(context.getFiler());
    }

    private void addPrefixConstant(TypeSpec.Builder classBuilder) {
        classBuilder.addField(
            FieldSpec.builder(
                String.class,
                "ROLE_PREFIX",
                Modifier.PRIVATE,
                Modifier.STATIC,
                Modifier.FINAL
            )
                .initializer("$S", "ROLE_")
                .build()
        );
    }

    private void addGetAttributeTypeMethod(TypeSpec.Builder classBuilder) {
        classBuilder.addMethod(
            MethodSpec.methodBuilder("getAttributeType")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(
                    ParameterizedTypeName.get(ClassName.get(Class.class), ClassName.get(roleEnum))
                )
                .addStatement("return $T.class", roleEnum)
                .build()
        );
    }

    private void addProvideMethod(TypeSpec.Builder classBuilder) {
        classBuilder.addMethod(
            MethodSpec.methodBuilder("provide")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(ClassName.get(roleEnum))
                .addCode(
                    """
                    return $T.ofNullable($T.getContext().getAuthentication())
                        .stream()
                        .flatMap(auth -> auth.getAuthorities().stream())
                        .map($T::getAuthority)
                        .map(authority -> authority.replace(ROLE_PREFIX, "").trim())
                        .map($T::valueOf)
                        .min($T.comparingInt($T::ordinal))
                        .orElseThrow();
                    """,
                    Optional.class,
                    SECURITY_CONTEXT_HOLDER,
                    GRANTED_AUTHORITY,
                    roleEnum,
                    Comparator.class,
                    roleEnum
                )
                .build()
        );
    }

    /**
     * Creates a new instance of {@link DefaultRoleAttributeProviderGenerator}.
     *
     * @param context the annotation processor context
     * @return a new RoleProviderGenerator instance
     */
    public static DefaultRoleAttributeProviderGenerator fromContext(
        AnnotationProcessorContext context
    ) {
        return new DefaultRoleAttributeProviderGenerator(
            context,
            context.getRoleEnumerationDefinition()
        );
    }
}
